#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
#ifndef PAYKIT_SWIFT_H
#define PAYKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="PayKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
enum CAPApiErrorCategory : NSInteger;
@class NSString;
@class NSCoder;

SWIFT_CLASS("_TtC6PayKit11CAPApiError")
@interface CAPApiError : NSError
@property (nonatomic, readonly) enum CAPApiErrorCategory category;
@property (nonatomic, readonly) NSInteger code;
@property (nonatomic, readonly, copy) NSString * _Nullable detail;
@property (nonatomic, readonly, copy) NSString * _Nullable field;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithDomain:(NSString * _Nonnull)domain code:(NSInteger)code userInfo:(NSDictionary<NSString *, id> * _Nullable)dict SWIFT_UNAVAILABLE;
@end

typedef SWIFT_ENUM(NSInteger, CAPApiErrorCategory, open) {
  CAPApiErrorCategoryAPI_ERROR = 0,
};

typedef SWIFT_ENUM(NSInteger, CAPApiErrorCode, open) {
  CAPApiErrorCodeINTERNAL_SERVER_ERROR = 0,
  CAPApiErrorCodeSERVICE_UNAVAILABLE = 1,
  CAPApiErrorCodeGATEWAY_TIMEOUT = 2,
};

@class CAPCashAppPayState;

SWIFT_PROTOCOL("_TtP6PayKit21CAPCashAppPayObserver_")
@protocol CAPCashAppPayObserver <NSObject>
- (void)stateDidChangeTo:(CAPCashAppPayState * _Nonnull)state;
@end


SWIFT_CLASS("_TtC6PayKit18CAPCashAppPayState")
@interface CAPCashAppPayState : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// An error with the Cash App Pay API that can manifest at runtime.
/// If an <code>APIError</code> is received, the integration is degraded and Cash App Pay functionality
/// should be temporarily removed from the app’s UI.
SWIFT_CLASS("_TtC6PayKit26CAPCashAppPayStateAPIError")
@interface CAPCashAppPayStateAPIError : CAPCashAppPayState
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

@class CAPCustomerRequest;
@class CAPCustomerRequestGrant;

/// CustomerRequest was approved. Update UI to show payment info or $cashtag.
SWIFT_CLASS("_TtC6PayKit26CAPCashAppPayStateApproved")
@interface CAPCashAppPayStateApproved : CAPCashAppPayState
@property (nonatomic, readonly, strong) CAPCustomerRequest * _Nonnull request;
@property (nonatomic, readonly, copy) NSArray<CAPCustomerRequestGrant *> * _Nonnull grants;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

@class CAPCreateCustomerRequestParams;

/// CustomerRequest is being created. For information only.
SWIFT_CLASS("_TtC6PayKit41CAPCashAppPayStateCreatingCustomerRequest")
@interface CAPCashAppPayStateCreatingCustomerRequest : CAPCashAppPayState
@property (nonatomic, readonly, strong) CAPCreateCustomerRequestParams * _Nonnull params;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end


/// SDK is redirecting to Cash App for authorization. Show loading indicator if desired.
SWIFT_CLASS("_TtC6PayKit26CAPCashAppPayStateDeclined")
@interface CAPCashAppPayStateDeclined : CAPCashAppPayState
@property (nonatomic, readonly, strong) CAPCustomerRequest * _Nonnull request;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end


/// An error in the integration that should be resolved before shipping to production.
/// Examples include authorization issues, incorrect brand IDs, validation errors, etc.
SWIFT_CLASS("_TtC6PayKit34CAPCashAppPayStateIntegrationError")
@interface CAPCashAppPayStateIntegrationError : CAPCashAppPayState
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end


/// A networking error, likely due to poor internet connectivity.
SWIFT_CLASS("_TtC6PayKit30CAPCashAppPayStateNetworkError")
@interface CAPCashAppPayStateNetworkError : CAPCashAppPayState
@property (nonatomic, readonly, strong) NSError * _Nonnull networkError;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end


/// Ready for a Create Customer Request to be initiated.
SWIFT_CLASS("_TtC6PayKit28CAPCashAppPayStateNotStarted")
@interface CAPCashAppPayStateNotStarted : CAPCashAppPayState
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end


/// SDK is redirecting to Cash App for authorization. Show loading indicator if desired.
SWIFT_CLASS("_TtC6PayKit25CAPCashAppPayStatePolling")
@interface CAPCashAppPayStatePolling : CAPCashAppPayState
@property (nonatomic, readonly, strong) CAPCustomerRequest * _Nonnull request;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end


/// CustomerRequest has been created, waiting for customer to press “Pay with Cash App Pay” button.
SWIFT_CLASS("_TtC6PayKit34CAPCashAppPayStateReadyToAuthorize")
@interface CAPCashAppPayStateReadyToAuthorize : CAPCashAppPayState
@property (nonatomic, readonly, strong) CAPCustomerRequest * _Nonnull request;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end


/// SDK is redirecting to Cash App for authorization. Show loading indicator if desired.
SWIFT_CLASS("_TtC6PayKit29CAPCashAppPayStateRedirecting")
@interface CAPCashAppPayStateRedirecting : CAPCashAppPayState
@property (nonatomic, readonly, strong) CAPCustomerRequest * _Nonnull request;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end


/// CustomerRequest is being refreshed as a result of the AuthFlowTriggers expiring.
/// Show loading indicator if desired.
SWIFT_CLASS("_TtC6PayKit28CAPCashAppPayStateRefreshing")
@interface CAPCashAppPayStateRefreshing : CAPCashAppPayState
@property (nonatomic, readonly, strong) CAPCustomerRequest * _Nonnull request;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end


/// An unexpected error. Please report any errors of this kind (and what caused them) to Cash App Developer Support.
SWIFT_CLASS("_TtC6PayKit33CAPCashAppPayStateUnexpectedError")
@interface CAPCashAppPayStateUnexpectedError : CAPCashAppPayState
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

@class CAPUpdateCustomerRequestParams;

/// CustomerRequest is being updated. For information only.
SWIFT_CLASS("_TtC6PayKit41CAPCashAppPayStateUpdatingCustomerRequest")
@interface CAPCashAppPayStateUpdatingCustomerRequest : CAPCashAppPayState
@property (nonatomic, readonly, strong) CAPCustomerRequest * _Nonnull request;
@property (nonatomic, readonly, strong) CAPUpdateCustomerRequestParams * _Nonnull params;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, CAPChannel, open) {
/// The customer is redirected to Cash App by a mobile application.
/// Use this channel for native apps on a customer’s device.
  CAPChannelIN_APP = 0,
/// The customer presents or scans a QR code at a physical location to approve the request.
  CAPChannelIN_PERSON = 1,
/// The customer scans a QR code or is redirected to Cash App by a website.
/// Not recommended for mobile applications.
  CAPChannelONLINE = 2,
};

@class CAPPaymentAction;
@class NSURL;

SWIFT_CLASS("_TtC6PayKit30CAPCreateCustomerRequestParams")
@interface CAPCreateCustomerRequestParams : NSObject
@property (nonatomic, readonly, copy) NSArray<CAPPaymentAction *> * _Nonnull actions;
@property (nonatomic, readonly, copy) NSString * _Nonnull channel;
@property (nonatomic, readonly, copy) NSURL * _Nonnull redirectURL;
@property (nonatomic, readonly, copy) NSString * _Nullable referenceID;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSString *> * _Nullable metadata;
- (nonnull instancetype)initWithActions:(NSArray<CAPPaymentAction *> * _Nonnull)actions channel:(enum CAPChannel)channel redirectURL:(NSURL * _Nonnull)redirectURL referenceID:(NSString * _Nullable)referenceID metadata:(NSDictionary<NSString *, NSString *> * _Nullable)metadata OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithActions:(NSArray<CAPPaymentAction *> * _Nonnull)actions redirectURL:(NSURL * _Nonnull)redirectURL referenceID:(NSString * _Nullable)referenceID metadata:(NSDictionary<NSString *, NSString *> * _Nullable)metadata OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, CAPCurrency, open) {
  CAPCurrencyUSD = 0,
};

@class CAPCustomerRequestAuthFlowTriggers;
@class NSDate;
@class CAPCustomerRequestOrigin;
@class CAPCustomerRequestRequesterProfile;
@class CAPCustomerRequestCustomerProfile;

SWIFT_CLASS("_TtC6PayKit18CAPCustomerRequest")
@interface CAPCustomerRequest : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly, copy) NSString * _Nonnull status;
@property (nonatomic, readonly, copy) NSArray<CAPPaymentAction *> * _Nonnull actions;
@property (nonatomic, readonly, strong) CAPCustomerRequestAuthFlowTriggers * _Nullable authFlowTriggers;
@property (nonatomic, readonly, copy) NSURL * _Nullable redirectURL;
@property (nonatomic, readonly, copy) NSDate * _Nonnull createdAt;
@property (nonatomic, readonly, copy) NSDate * _Nonnull updatedAt;
@property (nonatomic, readonly, copy) NSDate * _Nonnull expiresAt;
@property (nonatomic, readonly, strong) CAPCustomerRequestOrigin * _Nullable origin;
@property (nonatomic, readonly, copy) NSString * _Nonnull channel;
@property (nonatomic, readonly, copy) NSArray<CAPCustomerRequestGrant *> * _Nullable grants;
@property (nonatomic, readonly, copy) NSString * _Nullable referenceID;
@property (nonatomic, readonly, strong) CAPCustomerRequestRequesterProfile * _Nullable requesterProfile;
@property (nonatomic, readonly, strong) CAPCustomerRequestCustomerProfile * _Nullable customerProfile;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSString *> * _Nullable metadata;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6PayKit34CAPCustomerRequestAuthFlowTriggers")
@interface CAPCustomerRequestAuthFlowTriggers : NSObject
@property (nonatomic, readonly, copy) NSURL * _Nonnull qrCodeImageURL;
@property (nonatomic, readonly, copy) NSURL * _Nonnull qrCodeSVGURL;
@property (nonatomic, readonly, copy) NSURL * _Nonnull mobileURL;
@property (nonatomic, readonly, copy) NSDate * _Nonnull refreshesAt;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6PayKit33CAPCustomerRequestCustomerProfile")
@interface CAPCustomerRequestCustomerProfile : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly, copy) NSString * _Nonnull cashtag;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6PayKit23CAPCustomerRequestGrant")
@interface CAPCustomerRequestGrant : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly, copy) NSString * _Nonnull customerID;
@property (nonatomic, readonly, strong) CAPPaymentAction * _Nonnull action;
@property (nonatomic, readonly, copy) NSString * _Nonnull status;
@property (nonatomic, readonly, copy) NSString * _Nonnull channel;
@property (nonatomic, readonly, copy) NSDate * _Nonnull createdAt;
@property (nonatomic, readonly, copy) NSDate * _Nonnull updatedAt;
@property (nonatomic, readonly, copy) NSDate * _Nullable expiresAt;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6PayKit24CAPCustomerRequestOrigin")
@interface CAPCustomerRequestOrigin : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
@property (nonatomic, readonly, copy) NSString * _Nullable id;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6PayKit34CAPCustomerRequestRequesterProfile")
@interface CAPCustomerRequestRequesterProfile : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSURL * _Nonnull logoURL;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, CAPEndpoint, open) {
  CAPEndpointProduction = 0,
  CAPEndpointSandbox = 1,
  CAPEndpointStaging = 2,
};

enum CAPIntegrationErrorCategory : NSInteger;

SWIFT_CLASS("_TtC6PayKit19CAPIntegrationError")
@interface CAPIntegrationError : NSError
@property (nonatomic, readonly) enum CAPIntegrationErrorCategory category;
@property (nonatomic, readonly) NSInteger code;
@property (nonatomic, readonly, copy) NSString * _Nullable detail;
@property (nonatomic, readonly, copy) NSString * _Nullable field;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithDomain:(NSString * _Nonnull)domain code:(NSInteger)code userInfo:(NSDictionary<NSString *, id> * _Nullable)dict SWIFT_UNAVAILABLE;
@end

typedef SWIFT_ENUM(NSInteger, CAPIntegrationErrorCategory, open) {
  CAPIntegrationErrorCategoryAUTHENTICATION_ERROR = 0,
  CAPIntegrationErrorCategoryBRAND_ERROR = 1,
  CAPIntegrationErrorCategoryMERCHANT_ERROR = 2,
  CAPIntegrationErrorCategoryINVALID_REQUEST_ERROR = 3,
  CAPIntegrationErrorCategoryRATE_LIMIT_ERROR = 4,
};

typedef SWIFT_ENUM(NSInteger, CAPIntegrationErrorCode, open) {
  CAPIntegrationErrorCodeUNAUTHORIZED = 0,
  CAPIntegrationErrorCodeCLIENT_DISABLED = 1,
  CAPIntegrationErrorCodeFORBIDDEN = 2,
  CAPIntegrationErrorCodeVALUE_TOO_LONG = 3,
  CAPIntegrationErrorCodeVALUE_TOO_SHORT = 4,
  CAPIntegrationErrorCodeVALUE_EMPTY = 5,
  CAPIntegrationErrorCodeVALUE_REGEX_MISMATCH = 6,
  CAPIntegrationErrorCodeINVALID_URL = 7,
  CAPIntegrationErrorCodeVALUE_TOO_HIGH = 8,
  CAPIntegrationErrorCodeVALUE_TOO_LOW = 9,
  CAPIntegrationErrorCodeARRAY_LENGTH_TOO_LONG = 10,
  CAPIntegrationErrorCodeARRAY_LENGTH_TOO_SHORT = 11,
  CAPIntegrationErrorCodeINVALID_ARRAY_TYPE = 12,
  CAPIntegrationErrorCodeNOT_FOUND = 13,
  CAPIntegrationErrorCodeCONFLICT = 14,
  CAPIntegrationErrorCodeINVALID_STATE_TRANSITION = 15,
  CAPIntegrationErrorCodeCLIENT_NOT_FOUND = 16,
  CAPIntegrationErrorCodeRATE_LIMITED = 17,
  CAPIntegrationErrorCodeBRAND_NOT_FOUND = 18,
  CAPIntegrationErrorCodeMERCHANT_MISSING_ADDRESS_OR_SITE = 19,
};


SWIFT_CLASS("_TtC6PayKit8CAPMoney")
@interface CAPMoney : NSObject
@property (nonatomic, readonly) NSUInteger amount;
@property (nonatomic, readonly) enum CAPCurrency currency;
- (nonnull instancetype)initWithAmount:(NSUInteger)amount currency:(enum CAPCurrency)currency OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSData;

SWIFT_CLASS("_TtC6PayKit26CAPNetworkErrorInvalidJSON")
@interface CAPNetworkErrorInvalidJSON : NSError
@property (nonatomic, copy) NSData * _Nonnull data;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithDomain:(NSString * _Nonnull)domain code:(NSInteger)code userInfo:(NSDictionary<NSString *, id> * _Nullable)dict SWIFT_UNAVAILABLE;
@end

@class NSHTTPURLResponse;

SWIFT_CLASS("_TtC6PayKit22CAPNetworkErrorNilData")
@interface CAPNetworkErrorNilData : NSError
@property (nonatomic, strong) NSHTTPURLResponse * _Nonnull response;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithDomain:(NSString * _Nonnull)domain code:(NSInteger)code userInfo:(NSDictionary<NSString *, id> * _Nullable)dict SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC6PayKit25CAPNetworkErrorNoResponse")
@interface CAPNetworkErrorNoResponse : NSError
- (nonnull instancetype)initWithDomain:(NSString * _Nonnull)domain code:(NSInteger)code userInfo:(NSDictionary<NSString *, id> * _Nullable)dict OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6PayKit16CAPPaymentAction")
@interface CAPPaymentAction : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
@property (nonatomic, readonly, copy) NSString * _Nonnull scopeID;
@property (nonatomic, readonly, strong) CAPMoney * _Nullable money;
@property (nonatomic, readonly, copy) NSString * _Nullable accountReferenceID;
+ (CAPPaymentAction * _Nonnull)oneTimePaymentWithScopeID:(NSString * _Nonnull)scopeID money:(CAPMoney * _Nullable)money SWIFT_WARN_UNUSED_RESULT;
+ (CAPPaymentAction * _Nonnull)onFilePaymentWithScopeID:(NSString * _Nonnull)scopeID accountReferenceID:(NSString * _Nullable)accountReferenceID SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6PayKit18CAPUnexpectedError")
@interface CAPUnexpectedError : NSError
@property (nonatomic, readonly, copy) NSString * _Nonnull category;
@property (nonatomic, readonly, copy) NSString * _Nonnull codeMessage;
@property (nonatomic, readonly, copy) NSString * _Nullable detail;
@property (nonatomic, readonly, copy) NSString * _Nullable field;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithDomain:(NSString * _Nonnull)domain code:(NSInteger)code userInfo:(NSDictionary<NSString *, id> * _Nullable)dict SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC6PayKit30CAPUpdateCustomerRequestParams")
@interface CAPUpdateCustomerRequestParams : NSObject
@property (nonatomic, readonly, copy) NSArray<CAPPaymentAction *> * _Nonnull actions;
@property (nonatomic, readonly, copy) NSString * _Nullable referenceID;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSString *> * _Nullable metadata;
- (nonnull instancetype)initWithActions:(NSArray<CAPPaymentAction *> * _Nonnull)actions referenceID:(NSString * _Nullable)referenceID metadata:(NSDictionary<NSString *, NSString *> * _Nullable)metadata OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS_NAMED("ObjCWrapper")
@interface CAPCashAppPay : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkVersion;)
+ (NSString * _Nonnull)sdkVersion SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull RedirectNotification;)
+ (NSNotificationName _Nonnull)RedirectNotification SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) enum CAPEndpoint endpoint;
- (nonnull instancetype)initWithClientID:(NSString * _Nonnull)clientID endpoint:(enum CAPEndpoint)endpoint;
- (void)retrieveCustomerRequestWithId:(NSString * _Nonnull)id completion:(void (^ _Nonnull)(CAPCustomerRequest * _Nullable, NSError * _Nullable))completion;
- (void)createCustomerRequestWithParams:(CAPCreateCustomerRequestParams * _Nonnull)params;
- (void)updateCustomerRequest:(CAPCustomerRequest * _Nonnull)request with:(CAPUpdateCustomerRequestParams * _Nonnull)params;
- (void)authorizeCustomerRequest:(CAPCustomerRequest * _Nonnull)request;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



@interface CAPCashAppPay (SWIFT_EXTENSION(PayKit))
- (void)addObserver:(id <CAPCashAppPayObserver> _Nonnull)observer;
@end


#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
#ifndef PAYKIT_SWIFT_H
#define PAYKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="PayKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
enum CAPApiErrorCategory : NSInteger;
@class NSString;
@class NSCoder;

SWIFT_CLASS("_TtC6PayKit11CAPApiError")
@interface CAPApiError : NSError
@property (nonatomic, readonly) enum CAPApiErrorCategory category;
@property (nonatomic, readonly) NSInteger code;
@property (nonatomic, readonly, copy) NSString * _Nullable detail;
@property (nonatomic, readonly, copy) NSString * _Nullable field;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithDomain:(NSString * _Nonnull)domain code:(NSInteger)code userInfo:(NSDictionary<NSString *, id> * _Nullable)dict SWIFT_UNAVAILABLE;
@end

typedef SWIFT_ENUM(NSInteger, CAPApiErrorCategory, open) {
  CAPApiErrorCategoryAPI_ERROR = 0,
};

typedef SWIFT_ENUM(NSInteger, CAPApiErrorCode, open) {
  CAPApiErrorCodeINTERNAL_SERVER_ERROR = 0,
  CAPApiErrorCodeSERVICE_UNAVAILABLE = 1,
  CAPApiErrorCodeGATEWAY_TIMEOUT = 2,
};

@class CAPCashAppPayState;

SWIFT_PROTOCOL("_TtP6PayKit21CAPCashAppPayObserver_")
@protocol CAPCashAppPayObserver <NSObject>
- (void)stateDidChangeTo:(CAPCashAppPayState * _Nonnull)state;
@end


SWIFT_CLASS("_TtC6PayKit18CAPCashAppPayState")
@interface CAPCashAppPayState : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// An error with the Cash App Pay API that can manifest at runtime.
/// If an <code>APIError</code> is received, the integration is degraded and Cash App Pay functionality
/// should be temporarily removed from the app’s UI.
SWIFT_CLASS("_TtC6PayKit26CAPCashAppPayStateAPIError")
@interface CAPCashAppPayStateAPIError : CAPCashAppPayState
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

@class CAPCustomerRequest;
@class CAPCustomerRequestGrant;

/// CustomerRequest was approved. Update UI to show payment info or $cashtag.
SWIFT_CLASS("_TtC6PayKit26CAPCashAppPayStateApproved")
@interface CAPCashAppPayStateApproved : CAPCashAppPayState
@property (nonatomic, readonly, strong) CAPCustomerRequest * _Nonnull request;
@property (nonatomic, readonly, copy) NSArray<CAPCustomerRequestGrant *> * _Nonnull grants;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

@class CAPCreateCustomerRequestParams;

/// CustomerRequest is being created. For information only.
SWIFT_CLASS("_TtC6PayKit41CAPCashAppPayStateCreatingCustomerRequest")
@interface CAPCashAppPayStateCreatingCustomerRequest : CAPCashAppPayState
@property (nonatomic, readonly, strong) CAPCreateCustomerRequestParams * _Nonnull params;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end


/// SDK is redirecting to Cash App for authorization. Show loading indicator if desired.
SWIFT_CLASS("_TtC6PayKit26CAPCashAppPayStateDeclined")
@interface CAPCashAppPayStateDeclined : CAPCashAppPayState
@property (nonatomic, readonly, strong) CAPCustomerRequest * _Nonnull request;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end


/// An error in the integration that should be resolved before shipping to production.
/// Examples include authorization issues, incorrect brand IDs, validation errors, etc.
SWIFT_CLASS("_TtC6PayKit34CAPCashAppPayStateIntegrationError")
@interface CAPCashAppPayStateIntegrationError : CAPCashAppPayState
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end


/// A networking error, likely due to poor internet connectivity.
SWIFT_CLASS("_TtC6PayKit30CAPCashAppPayStateNetworkError")
@interface CAPCashAppPayStateNetworkError : CAPCashAppPayState
@property (nonatomic, readonly, strong) NSError * _Nonnull networkError;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end


/// Ready for a Create Customer Request to be initiated.
SWIFT_CLASS("_TtC6PayKit28CAPCashAppPayStateNotStarted")
@interface CAPCashAppPayStateNotStarted : CAPCashAppPayState
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end


/// SDK is redirecting to Cash App for authorization. Show loading indicator if desired.
SWIFT_CLASS("_TtC6PayKit25CAPCashAppPayStatePolling")
@interface CAPCashAppPayStatePolling : CAPCashAppPayState
@property (nonatomic, readonly, strong) CAPCustomerRequest * _Nonnull request;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end


/// CustomerRequest has been created, waiting for customer to press “Pay with Cash App Pay” button.
SWIFT_CLASS("_TtC6PayKit34CAPCashAppPayStateReadyToAuthorize")
@interface CAPCashAppPayStateReadyToAuthorize : CAPCashAppPayState
@property (nonatomic, readonly, strong) CAPCustomerRequest * _Nonnull request;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end


/// SDK is redirecting to Cash App for authorization. Show loading indicator if desired.
SWIFT_CLASS("_TtC6PayKit29CAPCashAppPayStateRedirecting")
@interface CAPCashAppPayStateRedirecting : CAPCashAppPayState
@property (nonatomic, readonly, strong) CAPCustomerRequest * _Nonnull request;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end


/// CustomerRequest is being refreshed as a result of the AuthFlowTriggers expiring.
/// Show loading indicator if desired.
SWIFT_CLASS("_TtC6PayKit28CAPCashAppPayStateRefreshing")
@interface CAPCashAppPayStateRefreshing : CAPCashAppPayState
@property (nonatomic, readonly, strong) CAPCustomerRequest * _Nonnull request;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end


/// An unexpected error. Please report any errors of this kind (and what caused them) to Cash App Developer Support.
SWIFT_CLASS("_TtC6PayKit33CAPCashAppPayStateUnexpectedError")
@interface CAPCashAppPayStateUnexpectedError : CAPCashAppPayState
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

@class CAPUpdateCustomerRequestParams;

/// CustomerRequest is being updated. For information only.
SWIFT_CLASS("_TtC6PayKit41CAPCashAppPayStateUpdatingCustomerRequest")
@interface CAPCashAppPayStateUpdatingCustomerRequest : CAPCashAppPayState
@property (nonatomic, readonly, strong) CAPCustomerRequest * _Nonnull request;
@property (nonatomic, readonly, strong) CAPUpdateCustomerRequestParams * _Nonnull params;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, CAPChannel, open) {
/// The customer is redirected to Cash App by a mobile application.
/// Use this channel for native apps on a customer’s device.
  CAPChannelIN_APP = 0,
/// The customer presents or scans a QR code at a physical location to approve the request.
  CAPChannelIN_PERSON = 1,
/// The customer scans a QR code or is redirected to Cash App by a website.
/// Not recommended for mobile applications.
  CAPChannelONLINE = 2,
};

@class CAPPaymentAction;
@class NSURL;

SWIFT_CLASS("_TtC6PayKit30CAPCreateCustomerRequestParams")
@interface CAPCreateCustomerRequestParams : NSObject
@property (nonatomic, readonly, copy) NSArray<CAPPaymentAction *> * _Nonnull actions;
@property (nonatomic, readonly, copy) NSString * _Nonnull channel;
@property (nonatomic, readonly, copy) NSURL * _Nonnull redirectURL;
@property (nonatomic, readonly, copy) NSString * _Nullable referenceID;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSString *> * _Nullable metadata;
- (nonnull instancetype)initWithActions:(NSArray<CAPPaymentAction *> * _Nonnull)actions channel:(enum CAPChannel)channel redirectURL:(NSURL * _Nonnull)redirectURL referenceID:(NSString * _Nullable)referenceID metadata:(NSDictionary<NSString *, NSString *> * _Nullable)metadata OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithActions:(NSArray<CAPPaymentAction *> * _Nonnull)actions redirectURL:(NSURL * _Nonnull)redirectURL referenceID:(NSString * _Nullable)referenceID metadata:(NSDictionary<NSString *, NSString *> * _Nullable)metadata OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, CAPCurrency, open) {
  CAPCurrencyUSD = 0,
};

@class CAPCustomerRequestAuthFlowTriggers;
@class NSDate;
@class CAPCustomerRequestOrigin;
@class CAPCustomerRequestRequesterProfile;
@class CAPCustomerRequestCustomerProfile;

SWIFT_CLASS("_TtC6PayKit18CAPCustomerRequest")
@interface CAPCustomerRequest : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly, copy) NSString * _Nonnull status;
@property (nonatomic, readonly, copy) NSArray<CAPPaymentAction *> * _Nonnull actions;
@property (nonatomic, readonly, strong) CAPCustomerRequestAuthFlowTriggers * _Nullable authFlowTriggers;
@property (nonatomic, readonly, copy) NSURL * _Nullable redirectURL;
@property (nonatomic, readonly, copy) NSDate * _Nonnull createdAt;
@property (nonatomic, readonly, copy) NSDate * _Nonnull updatedAt;
@property (nonatomic, readonly, copy) NSDate * _Nonnull expiresAt;
@property (nonatomic, readonly, strong) CAPCustomerRequestOrigin * _Nullable origin;
@property (nonatomic, readonly, copy) NSString * _Nonnull channel;
@property (nonatomic, readonly, copy) NSArray<CAPCustomerRequestGrant *> * _Nullable grants;
@property (nonatomic, readonly, copy) NSString * _Nullable referenceID;
@property (nonatomic, readonly, strong) CAPCustomerRequestRequesterProfile * _Nullable requesterProfile;
@property (nonatomic, readonly, strong) CAPCustomerRequestCustomerProfile * _Nullable customerProfile;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSString *> * _Nullable metadata;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6PayKit34CAPCustomerRequestAuthFlowTriggers")
@interface CAPCustomerRequestAuthFlowTriggers : NSObject
@property (nonatomic, readonly, copy) NSURL * _Nonnull qrCodeImageURL;
@property (nonatomic, readonly, copy) NSURL * _Nonnull qrCodeSVGURL;
@property (nonatomic, readonly, copy) NSURL * _Nonnull mobileURL;
@property (nonatomic, readonly, copy) NSDate * _Nonnull refreshesAt;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6PayKit33CAPCustomerRequestCustomerProfile")
@interface CAPCustomerRequestCustomerProfile : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly, copy) NSString * _Nonnull cashtag;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6PayKit23CAPCustomerRequestGrant")
@interface CAPCustomerRequestGrant : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull id;
@property (nonatomic, readonly, copy) NSString * _Nonnull customerID;
@property (nonatomic, readonly, strong) CAPPaymentAction * _Nonnull action;
@property (nonatomic, readonly, copy) NSString * _Nonnull status;
@property (nonatomic, readonly, copy) NSString * _Nonnull channel;
@property (nonatomic, readonly, copy) NSDate * _Nonnull createdAt;
@property (nonatomic, readonly, copy) NSDate * _Nonnull updatedAt;
@property (nonatomic, readonly, copy) NSDate * _Nullable expiresAt;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6PayKit24CAPCustomerRequestOrigin")
@interface CAPCustomerRequestOrigin : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
@property (nonatomic, readonly, copy) NSString * _Nullable id;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6PayKit34CAPCustomerRequestRequesterProfile")
@interface CAPCustomerRequestRequesterProfile : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSURL * _Nonnull logoURL;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, CAPEndpoint, open) {
  CAPEndpointProduction = 0,
  CAPEndpointSandbox = 1,
  CAPEndpointStaging = 2,
};

enum CAPIntegrationErrorCategory : NSInteger;

SWIFT_CLASS("_TtC6PayKit19CAPIntegrationError")
@interface CAPIntegrationError : NSError
@property (nonatomic, readonly) enum CAPIntegrationErrorCategory category;
@property (nonatomic, readonly) NSInteger code;
@property (nonatomic, readonly, copy) NSString * _Nullable detail;
@property (nonatomic, readonly, copy) NSString * _Nullable field;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithDomain:(NSString * _Nonnull)domain code:(NSInteger)code userInfo:(NSDictionary<NSString *, id> * _Nullable)dict SWIFT_UNAVAILABLE;
@end

typedef SWIFT_ENUM(NSInteger, CAPIntegrationErrorCategory, open) {
  CAPIntegrationErrorCategoryAUTHENTICATION_ERROR = 0,
  CAPIntegrationErrorCategoryBRAND_ERROR = 1,
  CAPIntegrationErrorCategoryMERCHANT_ERROR = 2,
  CAPIntegrationErrorCategoryINVALID_REQUEST_ERROR = 3,
  CAPIntegrationErrorCategoryRATE_LIMIT_ERROR = 4,
};

typedef SWIFT_ENUM(NSInteger, CAPIntegrationErrorCode, open) {
  CAPIntegrationErrorCodeUNAUTHORIZED = 0,
  CAPIntegrationErrorCodeCLIENT_DISABLED = 1,
  CAPIntegrationErrorCodeFORBIDDEN = 2,
  CAPIntegrationErrorCodeVALUE_TOO_LONG = 3,
  CAPIntegrationErrorCodeVALUE_TOO_SHORT = 4,
  CAPIntegrationErrorCodeVALUE_EMPTY = 5,
  CAPIntegrationErrorCodeVALUE_REGEX_MISMATCH = 6,
  CAPIntegrationErrorCodeINVALID_URL = 7,
  CAPIntegrationErrorCodeVALUE_TOO_HIGH = 8,
  CAPIntegrationErrorCodeVALUE_TOO_LOW = 9,
  CAPIntegrationErrorCodeARRAY_LENGTH_TOO_LONG = 10,
  CAPIntegrationErrorCodeARRAY_LENGTH_TOO_SHORT = 11,
  CAPIntegrationErrorCodeINVALID_ARRAY_TYPE = 12,
  CAPIntegrationErrorCodeNOT_FOUND = 13,
  CAPIntegrationErrorCodeCONFLICT = 14,
  CAPIntegrationErrorCodeINVALID_STATE_TRANSITION = 15,
  CAPIntegrationErrorCodeCLIENT_NOT_FOUND = 16,
  CAPIntegrationErrorCodeRATE_LIMITED = 17,
  CAPIntegrationErrorCodeBRAND_NOT_FOUND = 18,
  CAPIntegrationErrorCodeMERCHANT_MISSING_ADDRESS_OR_SITE = 19,
};


SWIFT_CLASS("_TtC6PayKit8CAPMoney")
@interface CAPMoney : NSObject
@property (nonatomic, readonly) NSUInteger amount;
@property (nonatomic, readonly) enum CAPCurrency currency;
- (nonnull instancetype)initWithAmount:(NSUInteger)amount currency:(enum CAPCurrency)currency OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSData;

SWIFT_CLASS("_TtC6PayKit26CAPNetworkErrorInvalidJSON")
@interface CAPNetworkErrorInvalidJSON : NSError
@property (nonatomic, copy) NSData * _Nonnull data;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithDomain:(NSString * _Nonnull)domain code:(NSInteger)code userInfo:(NSDictionary<NSString *, id> * _Nullable)dict SWIFT_UNAVAILABLE;
@end

@class NSHTTPURLResponse;

SWIFT_CLASS("_TtC6PayKit22CAPNetworkErrorNilData")
@interface CAPNetworkErrorNilData : NSError
@property (nonatomic, strong) NSHTTPURLResponse * _Nonnull response;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithDomain:(NSString * _Nonnull)domain code:(NSInteger)code userInfo:(NSDictionary<NSString *, id> * _Nullable)dict SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC6PayKit25CAPNetworkErrorNoResponse")
@interface CAPNetworkErrorNoResponse : NSError
- (nonnull instancetype)initWithDomain:(NSString * _Nonnull)domain code:(NSInteger)code userInfo:(NSDictionary<NSString *, id> * _Nullable)dict OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6PayKit16CAPPaymentAction")
@interface CAPPaymentAction : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
@property (nonatomic, readonly, copy) NSString * _Nonnull scopeID;
@property (nonatomic, readonly, strong) CAPMoney * _Nullable money;
@property (nonatomic, readonly, copy) NSString * _Nullable accountReferenceID;
+ (CAPPaymentAction * _Nonnull)oneTimePaymentWithScopeID:(NSString * _Nonnull)scopeID money:(CAPMoney * _Nullable)money SWIFT_WARN_UNUSED_RESULT;
+ (CAPPaymentAction * _Nonnull)onFilePaymentWithScopeID:(NSString * _Nonnull)scopeID accountReferenceID:(NSString * _Nullable)accountReferenceID SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6PayKit18CAPUnexpectedError")
@interface CAPUnexpectedError : NSError
@property (nonatomic, readonly, copy) NSString * _Nonnull category;
@property (nonatomic, readonly, copy) NSString * _Nonnull codeMessage;
@property (nonatomic, readonly, copy) NSString * _Nullable detail;
@property (nonatomic, readonly, copy) NSString * _Nullable field;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithDomain:(NSString * _Nonnull)domain code:(NSInteger)code userInfo:(NSDictionary<NSString *, id> * _Nullable)dict SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC6PayKit30CAPUpdateCustomerRequestParams")
@interface CAPUpdateCustomerRequestParams : NSObject
@property (nonatomic, readonly, copy) NSArray<CAPPaymentAction *> * _Nonnull actions;
@property (nonatomic, readonly, copy) NSString * _Nullable referenceID;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSString *> * _Nullable metadata;
- (nonnull instancetype)initWithActions:(NSArray<CAPPaymentAction *> * _Nonnull)actions referenceID:(NSString * _Nullable)referenceID metadata:(NSDictionary<NSString *, NSString *> * _Nullable)metadata OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS_NAMED("ObjCWrapper")
@interface CAPCashAppPay : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkVersion;)
+ (NSString * _Nonnull)sdkVersion SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull RedirectNotification;)
+ (NSNotificationName _Nonnull)RedirectNotification SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) enum CAPEndpoint endpoint;
- (nonnull instancetype)initWithClientID:(NSString * _Nonnull)clientID endpoint:(enum CAPEndpoint)endpoint;
- (void)retrieveCustomerRequestWithId:(NSString * _Nonnull)id completion:(void (^ _Nonnull)(CAPCustomerRequest * _Nullable, NSError * _Nullable))completion;
- (void)createCustomerRequestWithParams:(CAPCreateCustomerRequestParams * _Nonnull)params;
- (void)updateCustomerRequest:(CAPCustomerRequest * _Nonnull)request with:(CAPUpdateCustomerRequestParams * _Nonnull)params;
- (void)authorizeCustomerRequest:(CAPCustomerRequest * _Nonnull)request;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



@interface CAPCashAppPay (SWIFT_EXTENSION(PayKit))
- (void)addObserver:(id <CAPCashAppPayObserver> _Nonnull)observer;
@end


#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
