//
//  CPayManager.h
//  CPay
//
//  Created by long.zhao on 3/28/22.
//

#import <UIKit/UIKit.h>
#import "CPayDefines.h"

NS_ASSUME_NONNULL_BEGIN

@class CPayOrder;

@interface CPayManager : NSObject

#pragma mark - Utils

/// Set up access token
/// @param token is generated by CITCON
+ (void)setupTokenKey:(NSString *_Nonnull)token;

/// Set up runtime mode of SDK
/// @param mode is set to runtime mode.
+ (void)setupMode:(CPayMode)mode;

/// Returns the version of SDK
+ (NSString *_Nonnull)getVersion;

/// Call this function in -application: openURL
/// (iOS 9+): - (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
/// and in (iOS 8/7/6): - (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(nullable NSString *)sourceApplication annotation:(id)annotation
/// @param app An instance of UIApplication passed by AppDelegate
/// @param url An instance of NSURL passed by AppDelegate
/// @param callback is called when the processing is complete.
+ (BOOL)processOpenUrl:(UIApplication *_Nonnull)app
                   url:(NSURL *_Nonnull)url
       standbyCallback:(CPayOrderResultBlock _Nonnull)callback;

/// Call this function in -application: continueUserActivity:
/// @param userActivity An instance of NSUserActivity passed by AppDelegate
+ (BOOL)processUserActivity:(nonnull NSUserActivity *)userActivity;

/// Use order to initiate a transaction
/// @param order contains details of the transaction. See CPayOrder
/// @param completion is called when the payment is complete., see 'CPayOrderResultBlock' for details
+ (void)requestOrder:(CPayOrder *_Nonnull)order
          completion:(CPayOrderResultBlock _Nonnull)completion;

/// Inquire a transaction by transaction id.
/// @param transactionId of the transaction
/// @param order contains correct currency, vendor associated with the transaction
/// @param method "real" means it will be queried through the wallet gateway
/// @param completion is called when the query is complete, see 'CPayCheckResultBlock' for details
+ (void)inquireResult:(NSString *_Nonnull)transactionId
                order:(CPayOrder *_Nonnull)order
               method:(NSString *_Nonnull)method
           completion:(CPayCheckResultBlock _Nonnull )completion;

/// Inquire a transaction by reference id.
/// @param referenceId of the transaction
/// @param order contains correct currency, vendor associated with the transaction
/// @param method "real" means it will be queried through the wallet gateway
/// @param completion is called when the query is complete, see 'CPayCheckResultBlock' for details
+ (void)inquireResultByRef:(NSString *_Nonnull)referenceId
                     order:(CPayOrder *_Nonnull)order
                    method:(NSString *_Nonnull)method
                completion:(CPayCheckResultBlock _Nonnull)completion;

#pragma mark - App installed

/// Check if WeChat is installed
+ (BOOL)isWechatInstalled;

/// Check if Alipay is installed
+ (BOOL)isAlipayInstalled;

/// Check if Alipay HK is installed
+ (BOOL)isAlipayHKInstalled;

/// Check if KakaoPay is installed
+ (BOOL)isKakaoPayInstalled;

/// Check if UnionPay is installed
+ (BOOL)isUnionPayInstalled;

@end

NS_ASSUME_NONNULL_END
