# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


workspace 'CPayDemo'

target 'CPayDemo' do
	project 'CPayCocoapodsDemo.xcodeproj'
#  use_frameworks! :linkage => :static

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CPayDemo
    pod 'CPay', :path => '../'
end


#post_install do |installer|
#
#    installer.pods_project.build_configurations.each do |config|
#        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
#    end
#
#    
#    installer.pods_project.targets.each do |target|
#        target.build_configurations.each do |config|
#            #config.build_settings['SWIFT_VERSION'] = '5.1'
#
#            config.build_settings['ENABLE_BITCODE'] = 'NO'
#            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
##            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
#        end
#    end
#end
